name: Deploy new release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs: 
  build-test-deploy:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Rebuild # tests sometimes do not want to work without it
        run: dotnet build --configuration Release --no-restore --no-incremental
      - name: Run tests
        run: dotnet test --no-restore --verbosity normal
      - name: Pack
        run: dotnet pack --no-build --configuration Release /p:ContinuousIntegrationBuild=true
      - name: Deploy to GitHub
        run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.PUBLISH_PACKAGES_GITHUB }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      - name: Deploy to NuGet
        run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.PUBLISH_PACKAGES_NUGET }} --source https://api.nuget.org/v3/index.json
        