name: Test on push or pull-request
on:
  push:
    paths-ignore:
      - README.md
      - CONTRIBUTION.md
      - NOTICE.txt
      - VERSION_HISTORY.md
      - .gitignore
  pull_request:
    paths-ignore:
      - README.md
      - CONTRIBUTION.md
      - NOTICE.txt
      - VERSION_HISTORY.md
      - .gitignore
jobs:
  build-and-test:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: dotnet restore
      - name: Build (Debug)
        run: dotnet build --configuration Debug --no-restore
      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore
      - name: Rebuild (Debug) # tests sometimes do not want to work without it
        run: dotnet build --configuration Debug --no-incremental --no-restore
      - name: Rebuild (Release) # tests sometimes do not want to work without it
        run: dotnet build --configuration Release --no-incremental --no-restore
      - name: Run tests (Debug)
        run: dotnet test --configuration Debug --no-restore
      - name: Run tests (Release)
        run: dotnet test --configuration Release --no-restore